version: '2'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pi-hole
    mac_address: d0:ca:ab:cd:ef:01
    cap_add:
      - NET_ADMIN
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      # - 67/udp # Uncomment if you want to use Pi-Hole for DHCP
      - 80/tcp
      - 22/tcp
    environment:
      ServerIP: 10.0.10.5
      WEBPASSWORD: ${WEBPASSWORD}
      DNS1: 10.0.10.6
      DNS2: 
    volumes:
      - /var/lib/docker/pihole-unbound/pihole/volume:/pihole:rw
      - /var/lib/docker/pihole-unbound/pihole/config/hosts:/hosts:ro
      - /var/lib/docker/pihole-unbound/pihole/config/resolv.conf:/resolv.conf:ro
      - /var/lib/docker/pihole-unbound/pihole/config/dnsmasq.conf:/dnsmasq.d/02-network.conf:ro
      - /var/lib/docker/pihole-unbound/pihole/config/pihole-FTL.conf:/pihole/pihole-FTL.conf:ro
    networks:
      home:
        ipv4_address: 10.0.10.5
    restart: always
  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    hostname: syn-unbound
    mac_address: d0:ca:ab:cd:ef:02
    ports:
      - 53/tcp
      - 53/udp
    networks:
      home:
        ipv4_address: 10.0.10.6
    restart: always

networks:
  home:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 10.0.10.0/24
          gateway: 10.0.10.1
          ip_range: 10.0.10.5/30 # 10.0.10.5 and 10.0.10.6
